version: "3"

volumes:
  elasticsearch_db:

services:
  # -------------------------------------------
  # Logging infrastructure
  # -------------------------------------------
  # To run elasticsearch you must run
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    network_mode: host
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # - ELASTIC_PASSWORD=password
    #   - vm.max_map_count=262144
    # The following will store es data in your boot2docker vm
    volumes:
      - elasticsearch_db:/usr/share/elasticsearch
    
  # Accessible at http://localhost:5601
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    network_mode: host
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=password
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.6
    network_mode: host
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
    environment:
      - xpack.monitoring.elasticsearch.url=http://localhost:9200
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=password

  # Accessible at http://localhost:9411/zipkin/
  zipkin:
    image: openzipkin/zipkin
    network_mode: host
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://localhost:9200